name: My GitHub Actions Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: $({ matrix.node-version })
        ignore-prebuilt: true
        cache: 'npm'

    - name: Install dependencies
      run: npm install --force

    - name: Build code
      run: npm run build